project:
  type: website
  output-dir: _site

website:
  title: "unPopAdo"
  description: "Stata command: UN WPP2024 population estimates and projections"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/wbEPL/unPopAdo
        text: GitHub

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    anchor-sections: true
